### ISSUE TITLE
Unable to request API Keys

### ISSUE THREAD

**Issue by albertopasqualetto** [devinbaeten/bereal-time-history#11]
Title

**Comment by devinbaeten** [comment]
Hi @albertopasqualetto,

I am working on some changes to the API Key request process. I hope to soon improve response time and ensure everyone who wants an API key can get approval as fast as possible. I will close this once I have implemented the changes required.

If you still need an API key please reach out to me at [devin@devincreative.pro](mailto:devin@devincreative.pro).
