### ISSUE TITLE
Feature request: Timezone Translator

### ISSUE THREAD

**Issue by niklasR** [devinbaeten/bereal-time-history#8]
Hi,
just downloaded the CSV to check which BeReal Regions makes most sense for an upcoming holiday (priorities, right), based on historical data, i.e. compared the `europe-west` and `us-central` data with local time (UTC-3) in my case. Alas, Google Sheets isn't amazing at doing that; would be great if the site had a dropdown to shift the historical graphs to target timezones.

I might have a go at trying to implement it myself, but thought I'd leave a note here as it's not likely I will..

**Comment by devinbaeten** [comment]
Hi there,

I also think this would be quite useful. I will add it in the next update.

Thanks for the feedback!

**Comment by devinbaeten** [comment]
Introduced in v2.0.11
